# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ea8127b1158a3d9309350641bba0b88c07524f0879609b17ed3d48e741e06ec336e1cfbc4b4aafe2f992668a5840c1fc6e70efd84f02f847898485bbf82e15b

test:
  secret_key_base: 4e3a2d1ea2031c2adff25db521ec81315787fa40b9398a4a3a447cddee832f5d588007e5bab31db37475f3534f979401449e32583fb17a3a43e9e74520cd9d48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
